# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
addons:
  apt:
    packages:
    - libglu1-mesa-dev
env:
  global:
    - RGL_USE_NULL=TRUE
    - _R_CHECK_COMPACT_DATA_=FALSE
